default_connection_name = "neg-dev-sso"

[cli]
ignore_new_version_warning = false

  [cli.logs]
  save_logs = true
  path = "/Users/filiplivancic/Library/Application Support/snowflake/logs"
  level = "info"

[connections.filip-personal]
account = "biiyyqy-tx04262"
user = "Filpill"
role = "ACCOUNTADMIN"
authenticator = "PROGRAMMATIC_ACCESS_TOKEN"
token_file_path = "/Users/filiplivancic/.ssh/keys/PAT-tx04262-snowflake.txt"

[connections.trial-filip]
account = "irabuam-uk16676"
user = "filiplivancic"
role = "ACCOUNTADMIN"
authenticator = "PROGRAMMATIC_ACCESS_TOKEN"
token_file_path = "/Users/filiplivancic/.config/snowflake/PAT-uk16676-snowflake.txt"

[connections.neg-dev]
account = "neg-dev"
user = "filip.livancic@vivanti.com"
role = "DATA_ENGINEER"
warehouse = "WH_ENGINEERING"
authenticator = "SNOWFLAKE_JWT"
private_key_path = "/Users/filiplivancic/.ssh/keys/dbt_next_energy_filip_livancic.pem"

[connections.neg-test]
account = "neg-test"
user = "filip.livancic@vivanti.com"
role = "DATA_ENGINEER"
warehouse = "WH_ENGINEERING"
authenticator = "SNOWFLAKE_JWT"
private_key_path = "/Users/filiplivancic/.ssh/keys/dbt_next_energy_filip_livancic.pem"

[connections.neg-prod]
account = "neg-prod"
user = "filip.livancic@vivanti.com"
role = "DATA_ENGINEER"
warehouse = "WH_ENGINEERING"
authenticator = "SNOWFLAKE_JWT"
private_key_path = "/Users/filiplivancic/.ssh/keys/dbt_next_energy_filip_livancic.pem"

[connections.neg-dev-sso]
account = "neg-dev"
user = "filip.livancic@vivanti.com"
role = "DATA_ENGINEER"
warehouse = "WH_ENGINEERING"
authenticator = "externalbrowser"
client_store_temporary_credential = true
